### ISSUE TITLE
Duplicate bounties are created for certain users.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#737]
Duplicate bounties are being created for certain users. One is Tom S. The other is Jim.
<img width="1181" alt="Screenshot 2023-09-25 at 8 15 34 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/ad56e3b9-c27f-4264-af12-c6d37dd31680">
https://community.sphinx.chat/tickets?owner_id=024efa31d1e4f98bccc415b222c9d971866013ad6f95f7d1ed9e8be8e3355a36ff&created=1695644348
https://community.sphinx.chat/tickets?owner_id=024efa31d1e4f98bccc415b222c9d971866013ad6f95f7d1ed9e8be8e3355a36ff&created=1695644348

<img width="503" alt="Screenshot 2023-09-25 at 8 16 41 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/916099ab-23a6-4c84-a6b1-d0aaf5dcbb88">

community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1690574120

community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1690574120

**Comment by ecurrencyhodler** [comment]
The reason for duplicate bounties are that there were two profiles in our database.

**Comment by kevkevinpal** [comment]
we should test this on staging @elraphty merged a change that should fix this

**Comment by kevkevinpal** [comment]
did this on the db and I'm only seeing a count of 1
`SELECT owner_pub_key, COUNT(DISTINCT "owner_pub_key")  FROM people GROUP by owner_pub_key`

**Comment by ecurrencyhodler** [comment]
Okay. I still see duplicate bounties posted on our website. Is there a way to delete them?


![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/e6e71ad9-bfec-4285-950f-0fd83365b78c)
![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/584d7641-9723-4810-af64-0518bd9b7063)
![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/e5cbc012-66d2-4516-9629-b76033ee4bbf)
