### ISSUE TITLE
Remove hover from unclickable area

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#826]
Right now, the mouse turns into a finger in an area that is unclickable in the organization tab. This is bad UX because it makes the user believe the area outside of "manage" and "view bounties" are clickable. 

Let's change it so the mouse only turns into a finger in the clickable areas which is "manage" and "view bounties". 

https://github.com/stakwork/sphinx-tribes/assets/32662508/2932b678-ac0c-4dbf-9cb2-58b9fff50640

**Comment by VividhPandey003** [comment]
Hey I would like to work on this issue. Could you please tell me contribution guidelines and what file needs to be modified

**Comment by ecurrencyhodler** [comment]
Hi @VividhPandey003! Thanks for reaching out. This is currently in staging but not in production. You can find staging here: https://people-test.sphinx.chat/bounties

Just submit a PR to contribute and in the PR description mention that it closes this issue.

If you don't have a sphinx chat app and need one let me know and I can get one for you.

**Comment by VividhPandey003** [comment]
Hey @ecurrencyhodler, sure that would be great. Thanks

**Comment by ecurrencyhodler** [comment]
1. Download sphinx from here: https://buy.sphinx.chat/. You need testflight for iOS
2. Join as a new user and enter this code: connect::relay.swarm4.sphinx.chat::0276681167b8beb1e6113b259504ab7f9d84432cb3626b1f81b388154eb924073f

I can also assign a 100k satoshi bounty for this if you sign up to our website here: https://community.sphinx.chat/bounties

**Comment by VividhPandey003** [comment]
@ecurrencyhodler For testflight Its asking me a developer Invitation. Could you please help me regarding this

**Comment by ecurrencyhodler** [comment]
@VividhPandey003 hmmm you don't need a dev invitation. Just follow the steps here: https://testflight.apple.com/join/QoaCkJn6

I'm also not sure which file it is. and no you don't need to test on mobile.

**Comment by VividhPandey003** [comment]
Okay, I'm trying to find out the file. Thanks for being patient. I'll let uk if I face any issues

**Comment by VividhPandey003** [comment]
> Hi @VividhPandey003! Thanks for reaching out. This is currently in staging but not in production. You can find staging here: https://people-test.sphinx.chat/bounties

@ecurrencyhodler I am not able to view the interface of which you've shared the video. Could you please tell me how to **reproduce** that. The link which you've provided also doesn't show me the same interface.

**Comment by ecurrencyhodler** [comment]
Okay sign in, click on your profile on the top right, then click on the organizations tab. That should take you to this screen.

**Comment by elraphty** [comment]
> Hey I would like to work on this issue. Could you please tell me contribution guidelines and what file needs to be modified

The file you need to modify is OrgnizationView.tsx, the organization list is on this component, the change should be a one-line change on the Organization List styled component wrapper.

**Comment by VividhPandey003** [comment]
> > Hey I would like to work on this issue. Could you please tell me contribution guidelines and what file needs to be modified
> 
> The file you need to modify is OrgnizationView.tsx, the organization list is on this component, the change should be a one-line change on the Organization List styled component wrapper.

Okay thanks, working on it

**Comment by VividhPandey003** [comment]
@ecurrencyhodler @elraphty I have made a Pull Request regarding the change which I felt might be the issue. However I am not able to test this on my local machine.

![image](https://github.com/stakwork/sphinx-tribes/assets/91251535/8126f12d-67ea-43cc-b1e7-5b7fd32f2478)

Could you please teach me how to run and test this application on my local?

**Comment by VividhPandey003** [comment]
> Hey vivid! Do you want to give me your email on twitter? You can join our stand up and we can help you there. My twitter is @ecurrencyhodler

Sure thanks. Pinging you

**Comment by ecurrencyhodler** [comment]
Try again! Updated my settings

**Comment by VividhPandey003** [comment]
> Try again! Updated my settings

Done

**Comment by elraphty** [comment]
@VividhPandey003 The pointer cursor still shows in areas of the organization that are unclickable.

**Comment by VividhPandey003** [comment]
> @VividhPandey003 The pointer cursor still shows in areas of the organization that are unclickable.

okay, working on it

**Comment by VividhPandey003** [comment]
Hey @ecurrencyhodler @elraphty I have fixed the issue, checked it on my local as well. Could you please review my PR once?

**Comment by ecurrencyhodler** [comment]
We merged it @VividhPandey003. Great work! I paid out the bounty and you should see it in your sphinx chat.
